<?xml version="1.0" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
      <head>
            <title>$logintext$ &mdash; G&ouml;del-Gentzen Clojure Syndication Services Super System</title>
      </head>

      <body>
	$logintext$ 
	<form action="do_login" method="POST">
	  Username: <input name="name" type="text" /> <br />
	  Password: <input name="password" type="password" /> <br />
	  <input type="submit" value="Log In" />
	</form>
      </body>
</html>